### ISSUE TITLE
go-micro api 中请求后req.body中没有数据

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/questions#10]
使用micro api网关--handler=api，在micro new -type=api test/test-api之后产生的文件，并且main中注册consul。handler/test中call方法打印req.body没有任何东西.浏览器执行http://127.0.0.1:8080/test/call?name=zty
![深度截图_选择区域_20191113095020](https://user-images.githubusercontent.com/49492372/68726374-2fcbbc00-05fc-11ea-8940-2f864ef4ab74.png)
![深度截图_选择区域_20191113095258](https://user-images.githubusercontent.com/49492372/68726379-322e1600-05fc-11ea-829e-f7f7f1fc2e4d.png)
![深度截图_选择区域_20191113095430](https://user-images.githubusercontent.com/49492372/68726384-34907000-05fc-11ea-8f96-052b49d894e0.png)

**Comment by SkyWingZhang** [comment]
get,post
同样为空

**Comment by SkyWingZhang** [comment]
使用命令行curl -H 'Content-Type: application/json' -d '{data:123}' http://******************没有问题

**Comment by SkyWingZhang** [comment]
使用浏览器地址框get请求和vue中post请求均没有东西
![深度截图_选择区域_20191113101756](https://user-images.githubusercontent.com/49492372/68727313-fea0bb00-05fe-11ea-9922-e5264b53bdab.png)

**Comment by SkyWingZhang** [comment]
github    https://github.com/SkyWingZhang/test/

**Comment by SkyWingZhang** [comment]
代码地址 https://gitee.com/Sky-Wing/text

**Comment by SkyWingZhang** [comment]
用postman选中body选项也是没有数据。这样的数据接受方式，还不如来个json的字符串？

**Comment by taianrc** [comment]
请尝试
`
 axios.post('process/sort-add', data)
`

**Comment by taianrc** [comment]
> 用postman选中body选项也是没有数据。这样的数据接受方式，还不如来个json的字符串？

` micro --api_namespace oa.api api --handle
`

**Comment by weisd** [comment]
https://github.com/micro/go-micro/blob/master/api/handler/api/util.go#L37
看源码 ，content-type 不是application/x-www-form-urlencoded的时候，才会把http.request.body数据写到api.request.body里，而且被转成了string, 想传二进制数据的，慎用

**Comment by SkyWingZhang** [comment]
@weisd 原来这样子,非常感谢.但是不用application/x-www-form-urlencoded的时候怎么弄跨域,大神知道吗?前后端分离后得弄跨域

**Comment by hb-chen** [comment]
@SkyWingZhang 跨域需要`cors`，在[官方](https://github.com/micro/go-plugins/tree/master/micro)和[x-gateway](https://github.com/micro-in-cn/x-gateway/tree/master/pkg/plugin/micro)的插件里都有`cors`，可以参考
