### ISSUE TITLE
有关web 的问题

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro-in-cn/questions#18]
micro web 多个相同的web应用存在时，session 是同步的吗还是没有相关的功能，如果不是同步的那么怎么保证用户每次请求都路由到存在对应session的web应用。我们在micro中的这样问题是怎么解决的？

**Comment by weisd** [comment]
session用redis这些远程存储就好了，不存在本地不存在同步不同步的问题

**Comment by bluedragonflyliu** [comment]
thanks
