### ISSUE TITLE
[We Need You]我们需要一位善于管理问题的Leaders或者Owner

### ISSUE THREAD

**Issue by crazybber** [micro-in-cn/questions#19]
本仓库用于管理和搜集Micro/Go-Micro相关的各类问题以及FAQ，来帮助大家准确和全方位理解Go-Micro。
管理问题，是一项挑战，因为这意味着你要对Micro/Go-Micro有足够的了解或者有足够的了解兴趣，成为Micro China 的一份子，在帮助自己进步的同时，也帮助整个Micro China进步。

愿意接受挑战的小伙伴，请举手(回复到下方)，我们会及时联系你，如果你在我们的各种交流群里，可以直接呼叫Micro China的成员。

**Comment by SkyWingZhang** [comment]
1

**Comment by SkyWingZhang** [comment]
编程不仅是一门手艺，更是一种灵魂。越是简单得东西越能使人容易明白，越是灵活。如同go一样的Micro，简单，便捷，并且强大。愿Micro、能在服务端无所不能，令初学者着迷，老者深感其益。
接触了Micro，被他的微框架体系所吸引，正是这样，你可以随心定制。今天有幸为Micro贡献绵薄之力，本菜鸟一定知无不言。happy := new(year)

**Comment by crazybber** [comment]
@SkyWingZhang  you are welcome,let's begin from [questions](https://github.com/micro-community/questions)

@hb-chen @Allenxuxu @printfcoder
