### ISSUE TITLE
用protoc新生成的文件不正确。

### ISSUE THREAD

**Issue by jasionLaw** [micro-in-cn/questions#23]
操作目录：

> /Users/mike/Downloads/tutorials-master/examples/basic-practices/micro-api/api

执行的命令

> protoc --proto_path=/Users/mike/golang/src/github.com/micro/go-micro/api/ --go_out=. --micro_out=. proto/api.proto

目录结构与教程上面一致。

生成的文件

> api.pb.micro.go

> api.pb.go

api.pb.micro.go的具体内容：

```
// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/api.proto

package go_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package


```

没有了register***，***handle等的方法

> proton等版本3.10.1

**Comment by hb-chen** [comment]
`api.pb.micro.go`这又这些内容吗？
相应的service有生成没
可以把`protoc-gen-micro`删了，重新安装下看看

**Comment by jasionLaw** [comment]
> `api.pb.micro.go`这又这些内容吗？
> 相应的service有生成没
> 可以把`protoc-gen-micro`删了，重新安装下看看

重来了，还是没有生成。
在protoc-gen-micro提了issue

> yes, this is newest change to have generated files names like other tools do. xx.pb.plugin.go

> 我的回复but, it has not func like Register****,***Handler.I am so confused about this. Maybe give a doc?

**Comment by hb-chen** [comment]
我重新`go get github.com/micro/protoc-gen-micro`是对的，生成时对的，只是文件名变了

**Comment by jasionLaw** [comment]
知道什么问题了。   import的路径影响到不能加载。
