### ISSUE TITLE
api 网关如何使用consol

### ISSUE THREAD

**Issue by doubleycn** [micro-in-cn/questions#24]
如果我的srv服务使用的是consol做服务发现。那么在启动micro网关的时候如何使用consol呢？

例如：
  micro --registry=consul api

直接就提示错误了。

现在默认使用mdns做服务发现，consul挪到plugins里面去了。
那如何在启动网关的时候还使用consul作为服务发现呢？

在这个地方看到了类似问题。
https://github.com/micro/micro/issues/405

说是去写插件。例子在go-plugins 里面。
能具体说一下是哪个例子吗？

**Comment by xuhrc** [comment]
> 如果我的srv服务使用的是consol做服务发现。那么在启动micro网关的时候如何使用consol呢？
> 
> 例如：
> micro --registry=consul api
> 
> 直接就提示错误了。
> 
> 现在默认使用mdns做服务发现，consul挪到plugins里面去了。
> 那如何在启动网关的时候还使用consul作为服务发现呢？
> 
> 在这个地方看到了类似问题。
> [micro/micro#405](https://github.com/micro/micro/issues/405)
> 
> 说是去写插件。例子在go-plugins 里面。
> 能具体说一下是哪个例子吗？

**Comment by xuhrc** [comment]
[solution](https://github.com/micro/micro/issues/405#issuecomment-560331954)
