### ISSUE TITLE
使用micro new --type=api 的模板，没有自带consul包

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/questions#3]
new出来后，在go mod tidy获取各种包后，查看go.mod文件github.com/micro/go-micro  v1.4.0，但是这个github.com/micro/go-micro/registry/包中没有consul包，我改为v1.9.1版本后再执行go mod tidy命令拉取包，提示
![深度截图_选择区域_20191101160932](https://user-images.githubusercontent.com/49492372/68011341-05a40100-fcc2-11e9-8ccc-c9265df76b47.png)
请问如何解决

**Comment by SkyWingZhang** [comment]
![Uploading 深度截图_选择区域_20191101162226.png…]()
这是模板new出来go mod tidy后的结果。go.mod里go-micro版本为v1.4.0

**Comment by SkyWingZhang** [comment]
![深度截图_选择区域_20191101162226](https://user-images.githubusercontent.com/49492372/68012101-15bce000-fcc4-11e9-82f9-adf1d6ea6dd1.png)
这是模板new出来go mod tidy后的结果。go.mod里go-micro版本为v1.4.0

**Comment by yeaze** [comment]
貌似consul已经从默认中移除了，需要通过插件形式引入

**Comment by SkyWingZhang** [comment]
> 貌似consul已经从默认中移除了，需要通过插件形式引入

有没有插入方式。这一个正在跑的项目有点尴尬。

**Comment by yeaze** [comment]
import "github.com/micro/go-plugins/registry/consul"

**Comment by SkyWingZhang** [comment]
> import "github.com/micro/go-plugins/registry/consul"

事实上。这个包1.4.0版本已经不包含consul，所以，也引入不了。默认拉取的就是1.4.0。
改为1.9.1版本拉取就会提示图一错误

**Comment by SkyWingZhang** [comment]
> import "github.com/micro/go-plugins/registry/consul"

拉取时产生新的错误
![深度截图_选择区域_20191101171616](https://user-images.githubusercontent.com/49492372/68014747-5b30db80-fccb-11e9-8c6c-d81a7cbeebeb.png)

**Comment by yeaze** [comment]
在你的go.mod 文件下添加一行
`replace github.com/gogo/protobuf v0.0.0-20190410021324-65acae22fc9 => github.com/gogo/protobuf v0.0.0-20190723190241-65acae22fc9d`

**Comment by SkyWingZhang** [comment]
> 在你的go.mod 文件下添加一行
> `replace github.com/gogo/protobuf v0.0.0-20190410021324-65acae22fc9 => github.com/gogo/protobuf v0.0.0-20190723190241-65acae22fc9d`

好的，非常感谢
