### ISSUE TITLE
tunnel模块中的 Tunnel, Link, Channel, Session之间的关系是？

### ISSUE THREAD

**Issue by flashell** [micro-in-cn/questions#31]
虽然 [Building a global services network using Go, QUIC and Micro](https://blog.gopheracademy.com/advent-2019/building-a-microservices-network/)中有讲，但是在看源码时，仍然感觉云山雾罩，烦请大大们指导一下

**Comment by printfcoder** [comment]
Tunnel: 打通两个网络的隧道，比如两个地区，两个机房
Link：与当前Tunnel连接的Tunnel
Channel：在Tunnel两端的服务通信用的信道名
Session：就是会话，用于维持Tunnel连接上下文

**Comment by flashell** [comment]
thx
