### ISSUE TITLE
examples/proxy failed with: "service name is blank

### ISSUE THREAD

**Issue by flashell** [micro-in-cn/questions#32]
**os**: windows 10
**go-micro**: 1.18.0
**go**: 1.13

**steps:**

> 1. micro.exe proxy
> 2. go run rpc_server.go proxy.go
> 3. go run rpc_client.go  proxy.go

**output:** 
> {"id":"","result":null,"error":"{\"id\":\"go.micro.proxy\",\"code\":400,\"detail\":\"service name is blank\",\"status\":\"Bad Request\"}"}
在 micro官方问过这个问题，暂时无回应，也麻烦大大们指点一下

**Comment by printfcoder** [comment]
这个是早期的用法了，那时候proxy还是定位在sidecar模式，现在proxy是用来代理网络了。可以参考：[micro proxy](https://github.com/micro-in-cn/tutorials/tree/master/examples/senior-practices/micro-proxy)

**Comment by flashell** [comment]
难怪，thx
