### ISSUE TITLE
关于web调用svr的问题。

### ISSUE THREAD

**Issue by 2lingnil** [micro-in-cn/questions#36]
假设web接口调用svr，而且svr有多个节点。那么这里web调用的哪个节点的svr呢？micro是有默认的选择策略？能否自己对这个选择策略进行定制？

**Comment by hb-chen** [comment]
![filter strategy](https://user-images.githubusercontent.com/730866/72654655-655d9e80-39cb-11ea-955c-e36d2bef412e.png)
服务选择会经历这几个过程：
- `list`从注册中心查询服务
- `filter`通过筛选器对服务进行筛选，如版本、Label
- `strategy`负载均衡策略，在符合筛选条件的服务中再按策略选择服务，可以是随机、轮询等

针对你的问题可以使用`filter`和`strategy`来实现，都是可以自己定制的，具体看下[go-micro/client/selector](https://github.com/micro/go-micro/tree/master/client/selector)模块
