### ISSUE TITLE
请教有没有方法把其他语言（python，php）实现的web接口，grpc服务接入到micro中

### ISSUE THREAD

**Issue by 2lingnil** [micro-in-cn/questions#38]
举个例子：A服务用php实现，b服务使用python实现。
然后，现在把他们接入micor中，原来它们的所有请求，现在不直接处理，而是通过micro 转发给A，B。

**Comment by printfcoder** [comment]
只能走http调用A,B。micro网关只能代理go-micro风格的应用接口。

**Comment by 2lingnil** [comment]
> 只能走http调用A,B。micro网关只能代理go-micro风格的应用接口。

已经走http了，感谢。 @printfcoder
