### ISSUE TITLE
"id":"go.micro.client.transport","code":500,"detail":"malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"","status":"Internal Server Error"

### ISSUE THREAD

**Issue by SkyWingZhang** [micro-in-cn/questions#41]
"id":"go.micro.client.transport","code":500,"detail":"malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"","status":"Internal Server Error"

遇到这样的错误，要确认服务的go-micro和micro api网关的micro版本一致。如都是v1.18.0。
在go.mod文件里可以查看各包版本号，在go.mod里把版本号改为一致

**Comment by blueapplehe** [comment]
又出现这个问题了，到到底是怎么回事？
