### ISSUE TITLE
client重试

### ISSUE THREAD

**Issue by liqiangno1** [micro-in-cn/questions#64]
使用示例得demo方法，https://github.com/micro-in-cn/starter-kit/blob/master/console/api/client/account.go，通过wrapper将client注入到context中再获取。
这个时候怎么设置client得重试次数呢？
我在main方法中如下设置
```
service.Client().Init(
  client.Retries(2),
)

单步调试，在这里获取到得client retry参数确实是2
client := account.NewAccountService("go.micro.srv.account", service.Client())，
但是当发起请求时，然后注入到context时，查看这时候client得retry已经变成1了
ctx = context.WithValue(ctx, exampleKey{}, client)
```

**Comment by printfcoder** [comment]
@hb-chen 波哥麻烦解惑

**Comment by hb-chen** [comment]
应该是`service.Client().Init()`的时机不对，这个要在`micro.WrapHandler(client.AccountWrapper(service))`之前，否则注入到`context`中的`client`是旧的，就以 https://github.com/micro-in-cn/starter-kit/blob/master/console/api 为例，Client的初始点如下:
```go
        // Initialise service
	service.Init(
		// 流量染色
		micro.WrapClient(chain.NewClientWrapper()),
		// 路由筛选
		micro.WrapCall(router_filter.NewCallWrapper()),
	)

	service.Client().Init(client2.Retries(2))

	service.Init(
		// create wrap for the Example srv client
		micro.WrapHandler(client.AccountWrapper(service)),
		micro.WrapHandler(validate.NewHandlerWrapper()),
		micro.WrapCall(validate.NewCallWrapper()),
		// Tracing仅由Gateway控制，在下游服务中仅在有Tracing时启动
		micro.WrapHandler(opentracing.NewHandlerWrapper(t)),         // server端handler接受请求
		micro.WrapSubscriber(opentracing.NewSubscriberWrapper(nil)), // server端subscriber接受消息
		micro.WrapClient(opentracing.NewClientWrapper(nil)),         // client端发起请求，包括Call()、Stream()、Publish()
		micro.WrapCall(opentracing.NewCallWrapper(t)),               // client端发起请求，仅Call()
	)
```

在使用service.Init()以及其他组件的Init时最好拆开，多次Init()，否则容易出现不达预期的初始化过程，因为在做Option是会出现组件替换、覆盖等问题，一般可以遵循这个过程

- server & client
   - broker
      - registry
   - transport
   - selector
   - name̵ version……

**Comment by liqiangno1** [comment]
> 应该是`service.Client().Init()`的时机不对，这个要在`micro.WrapHandler(client.AccountWrapper(service))`之前，否则注入到`context`中的`client`是旧的，就以 https://github.com/micro-in-cn/starter-kit/blob/master/console/api 为例，Client的初始点如下:
> 
> ```go
>         // Initialise service
> 	service.Init(
> 		// 流量染色
> 		micro.WrapClient(chain.NewClientWrapper()),
> 		// 路由筛选
> 		micro.WrapCall(router_filter.NewCallWrapper()),
> 	)
> 
> 	service.Client().Init(client2.Retries(2))
> 
> 	service.Init(
> 		// create wrap for the Example srv client
> 		micro.WrapHandler(client.AccountWrapper(service)),
> 		micro.WrapHandler(validate.NewHandlerWrapper()),
> 		micro.WrapCall(validate.NewCallWrapper()),
> 		// Tracing仅由Gateway控制，在下游服务中仅在有Tracing时启动
> 		micro.WrapHandler(opentracing.NewHandlerWrapper(t)),         // server端handler接受请求
> 		micro.WrapSubscriber(opentracing.NewSubscriberWrapper(nil)), // server端subscriber接受消息
> 		micro.WrapClient(opentracing.NewClientWrapper(nil)),         // client端发起请求，包括Call()、Stream()、Publish()
> 		micro.WrapCall(opentracing.NewCallWrapper(t)),               // client端发起请求，仅Call()
> 	)
> ```
> 
> 在使用service.Init()以及其他组件的Init时最好拆开，多次Init()，否则容易出现不达预期的初始化过程，因为在做Option是会出现组件替换、覆盖等问题，一般可以遵循这个过程
> 
> * server & client
>   
>   * broker
>     
>     * registry
>   * transport
>   * selector
>   * name̵ version……
确实是顺序有问题，我得demo是这样得：
```
service.Client().Init(
	client2.Retries(5),
)

//service.Init里面有个s.once.Do方法，这个只执行一次，应该里面会注入对应得环境变量，导致被覆盖了，在service.Client().Init前面写一个空得service.Init()，然后正常了
service.Init(
	micro.WrapHandler(client.HelloWrapper(service)),
)
```
我还是按照建议注入环境变量吧，感觉这样好点。
