### ISSUE TITLE
如何调用第三方http服务？

### ISSUE THREAD

**Issue by liqiangno1** [micro-in-cn/questions#65]
如何优雅得调用第三方http服务呢？比如支付宝，微信支付接口等？
1.原生net/http库，自己封装，比较简单，但是想使用go micro生态下得熔断，重试等组件，就不能用了。
2. 使用go micro插件得http client插件。但是好像必须得先注册到consul，etcd等注册发现组件才可以调用。
其实也引申出来对于异构服务，比如其他语言写得服务只提供http接口，如何更好得互相调用呢
有没有这方面得最佳实践呢？感谢！

**Comment by printfcoder** [comment]
目前来说不可以，而且可能也不会得到支持，异构系统不论是语言还是框架，互相调用又要上下文流程对称，是不可能的。

如果想调用第三方又要熔断、重试，目前只能自定义包装一下http client就可以了，这样的例子github上应该是很多的。

**Comment by liqiangno1** [comment]
> 目前来说不可以，而且可能也不会得到支持，异构系统不论是语言还是框架，互相调用又要上下文流程对称，是不可能的。
> 
> 如果想调用第三方又要熔断、重试，目前只能自定义包装一下http client就可以了，这样的例子github上应该是很多的。

好吧，我再看一下
