### ISSUE TITLE
micro v2.9.0

### ISSUE THREAD

**Issue by t5w0rd** [micro-in-cn/questions#69]
全部升级完2.0之后api网关失效了。
例如：
micro service 名字为xxx.srv.greeter，方法为Greeter.Call
micro --auth_namespace=xxx api --namespace=xxx --handler=rpc

调用http://localhost:8080/srv/greeter/greeter/call，会报服务找不到的错误

因为最新的micro里使用了service.Endpoints[].Metadata来获取服务名，但注册表里这个必定是空。

希望尽早修复！

**Comment by printfcoder** [comment]
这个目前看应该不会修复，这需求破坏性更新，对于老接口老使用方式只能停留在老的版本。

**Comment by t5w0rd** [comment]
谢谢回复，这个问题已经解决了。
