### ISSUE TITLE
有关micro web的问题

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro-in-cn/questions#7]
micro web 默认情况下访问对应IP的8082端口会有一个管理页面，怎么才能不要这个管理界面，web 应用又能正常使用，因为这个界面暴漏太多东西，没有证书。

**Comment by printfcoder** [comment]
这个是内部界面，目前没有开关关掉，如果只是想要一个反向代理，可以使用
`micro api --handler=web`

**Comment by bluedragonflyliu** [comment]
谢谢帮助
