### ISSUE TITLE
micro env 的问题

### ISSUE THREAD

**Issue by ifsc01** [micro-in-cn/questions#74]
```
micro env
  local      none
* server     127.0.0.1:8081
  platform   proxy.m3o.com
```

这几个有什么区别， 没找到文档

另外   platform   proxy.m3o.com 是什么

**Comment by printfcoder** [comment]
env 是查看/设置本地运行环境变量的指令。见cli.go中的env部分。

不存在区别，它们只是不同的变量而已。platofrm是go-micro应用上云的注册后台地址，本地运行可忽略。

**Comment by ifsc01** [comment]
那什么时候用 local 什么时候用server呢

Shu xian <notifications@github.com> 于2020年7月6日周一 上午9:15写道：
